-- supabase/migrations/20260405100000_create_match_feedback.sql

-- 1. Create the match_feedback table
CREATE TABLE public.match_feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    target_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    match_score INTEGER NOT NULL,
    feedback_rating INTEGER NOT NULL,
    reasons TEXT[] DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Add a UNIQUE constraint on (user_id, target_id)
ALTER TABLE public.match_feedback
ADD CONSTRAINT unique_user_target_feedback UNIQUE (user_id, target_id);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.match_feedback ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies
-- Users can only insert feedback for themselves
CREATE POLICY "Enable insert for authenticated users only"
ON public.match_feedback
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can only update their own feedback
CREATE POLICY "Enable update for users based on user_id"
ON public.match_feedback
FOR UPDATE USING (auth.uid() = user_id);

-- Users can view their own feedback
CREATE POLICY "Enable read access for own feedback"
ON public.match_feedback
FOR SELECT USING (auth.uid() = user_id);

-- 5. Add comments for clarity
COMMENT ON TABLE public.match_feedback IS 'Stores feedback from users about the quality of their matches.';
COMMENT ON COLUMN public.match_feedback.user_id IS 'The user providing the feedback.';
COMMENT ON COLUMN public.match_feedback.target_id IS 'The user profile being rated.';
COMMENT ON COLUMN public.match_feedback.match_score IS 'The original compatibility score generated by the system.';
COMMENT ON COLUMN public.match_feedback.feedback_rating IS 'User-provided rating, e.g., 1 for thumbs up, -1 for thumbs down.';
COMMENT ON COLUMN public.match_feedback.reasons IS 'Array of reasons for a negative feedback rating.';
