-- supabase/migrations/20260402120000_create_user_activity_logs.sql

-- 1. Create the user_activity_logs table
CREATE TABLE public.user_activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. Add comments to the table and columns for clarity
COMMENT ON TABLE public.user_activity_logs IS 'Tracks key user actions for auditing and administrative review.';
COMMENT ON COLUMN public.user_activity_logs.user_id IS 'The user who performed the action.';
COMMENT ON COLUMN public.user_activity_logs.action_type IS 'The type of action performed (e.g., ''login'', ''create_listing'').';
COMMENT ON COLUMN public.user_activity_logs.metadata IS 'Additional details about the action, such as the ID of the created resource.';

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.user_activity_logs ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS policies
--    - Admins can see all activity logs.
--    - Users can only see their own activity logs.
CREATE POLICY "Allow admins full access"
ON public.user_activity_logs
FOR SELECT
TO authenticated
USING (
  (SELECT is_admin FROM public.profiles WHERE id = auth.uid()) = TRUE
);

CREATE POLICY "Allow users to view their own activity"
ON public.user_activity_logs
FOR SELECT
TO authenticated
USING (
  user_id = auth.uid()
);

-- 5. Create an index for faster lookups on user_id
CREATE INDEX idx_user_activity_logs_user_id ON public.user_activity_logs(user_id);
